# Generated by Django 5.0.7 on 2024-07-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('start_city', models.CharField(max_length=255)),
                ('end_city', models.CharField(max_length=255)),
                ('current_city', models.CharField(max_length=255)),
                ('create_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('on_way', 'On Way'), ('delivered', 'Delivered'), ('issued', 'Issued')], max_length=20)),
            ],
        ),
    ]
