# Generated by Django 5.0.7 on 2024-07-12 01:55

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userinput_alter_order_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=22)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Created'), ('В пути', 'On Way'), ('Доставлен', 'Delivered'), ('Выдан', 'Issued')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
